import { EventEmitter, ElementRef, AfterContentInit } from "@angular/core";
import { CompleterItem } from "./completer-item";
export declare class CompleterListCmp implements AfterContentInit {
    private listElm;
    results: CompleterItem[];
    matchClass: string;
    searchStr: string;
    textSearching: string;
    searching: boolean;
    textNoResults: string;
    displaySearching: boolean;
    selected: EventEmitter<CompleterItem>;
    list: any;
    currentIndex: number;
    private isScrollOn;
    private dd;
    constructor(listElm: ElementRef);
    ngAfterContentInit(): void;
    onClick(result: CompleterItem): void;
    hoverRow(index: number): void;
    incIndex(): void;
    decIndex(): void;
    unselect(): void;
    toTop(): void;
    private dropdownRow();
    private dropdownHeight();
    private dropdownScrollTopTo(offset);
    private dropdownRowOffsetHeight(row);
    private dropdownRowTop();
}
