import { EventEmitter, OnInit } from "@angular/core";
import { ControlValueAccessor } from "@angular/forms";
import { CompleterData } from "./services/completer-data";
import { CompleterItem } from "./completer-item";
import "rxjs/add/operator/catch";
export declare class CompleterCmp implements OnInit, ControlValueAccessor {
    dataService: CompleterData;
    searchFields: string;
    inputName: string;
    pause: number;
    minSearchLength: number;
    maxChars: number;
    overrideSuggested: boolean;
    clearSelected: boolean;
    placeholder: string;
    matchClass: string;
    textSearching: string;
    textNoResults: string;
    fieldTabindex: number;
    autoMatch: boolean;
    disableInput: boolean;
    selected: EventEmitter<CompleterItem>;
    private listCmp;
    private searchStr;
    private searching;
    private showDropdown;
    private displayNoResults;
    private searchTimer;
    private hideTimer;
    private displaySearching;
    private selectedObject;
    private results;
    private _onTouchedCallback;
    private _onChangeCallback;
    constructor();
    value: any;
    onTouched(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    keyupHandler(event: any): void;
    keydownHandler(event: any): void;
    ngOnInit(): void;
    selectResult(result: any): void;
    hideResults(): void;
    onBlur(): void;
    private initResults();
    private searchTimerComplete(str);
    private clearResults();
    private handleOverrideSuggestions(event?);
    private setInputString(str);
    private callOrAssign(value);
    private handleError(error);
}
